name: ObsydianPrisons
version: '1.0-SNAPSHOT'
main: com.obsydian.obsydianprisons.ObsydianPrisons
api-version: '1.21'
depend:
  - Vault
  - iConomyUnlocked
commands:
  sell:
    description: Sells all items in inventory
    usage: /<command>
    aliases:
      - sellall
  enderchest:
    description: Opens your ender chest
    usage: /<command>
    aliases: [ ec, echest ]
  servinf:
    description: Hardware info
  start:
    description: Starts the player on the server
    usage: /<command>
    
